apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-data
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ibmc-block-bronze
